### ISSUE TITLE
Tracking Issue: Function Pointers

### ISSUE THREAD

**Issue by Shizcow** [Shizcow/hotpatch#8]
Currently, there's several extra layers of indirection on every `Patchable` function call. In the past several weeks I've been experimenting with ways to remove this, and finally have a lead. I have found the function pointer approach to be more forgiving with reference lifetimes, allowing for method patching to __actually work__. This issue tracks progress on integration.

- [x] Figure out how to actually do it
- [x] Reconfigure library to handle all incoming `Patchable` declarations
- [x] Update `#[patchable]` to generate the correct init code
- [x] Fix and set up importing
- [x] Update `#[patch]` to interface with new imports
- [x] Ensure backwards compatibility with previous version
- [x] Docs!
